steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'sync-photos'            # Funktion nimi GCP:ssä
      - '--gen2'                 # Suositellaan 2. sukupolven Cloud Functionsia
      - '--region=$_REGION'
      - '--source=.'
      - '--entry-point=sync_photos'
      - '--runtime=python313'    # Vaihdettu Python 3.13 -versioon
      - '--trigger-http'         # Koska funktiosi ottaa vastaan 'request'-parametrin
      - '--timeout=540s'         # Maksimiaika, jotta isot albumit ehtivät latautua
      - '--memory=512MB'         # Riittävästi muistia kuvien käsittelyyn ja välimuistiin
      
      # Ympäristömuuttujat välitetään Cloud Build -triggerin substituutioista:
      - '--set-env-vars=ALBUM_ID=$_ALBUM_ID,BUCKET_NAME=$_BUCKET_NAME'
      
      # Salaisuudet haetaan Secret Managerista (funktiolla pitää olla lukuoikeus näihin):
      - '--set-secrets=CLIENT_ID=projects/$PROJECT_ID/secrets/CLIENT_ID:latest,CLIENT_SECRET=projects/$PROJECT_ID/secrets/CLIENT_SECRET:latest,REFRESH_TOKEN=projects/$PROJECT_ID/secrets/REFRESH_TOKEN:latest'

substitutions:
  _REGION: 'europe-north1' # Oletusalue (esim. Suomi/Hamina)
  
  # HUOM: Seuraavat arvot on suositeltavaa jättää tyhjiksi tässä tiedostossa
  # ja määrittää ne suoraan Google Cloud Build -triggerin "Substitution variables" -osiossa.
  # _ALBUM_ID: ''
  # _BUCKET_NAME: ''

options:
  logging: CLOUD_LOGGING_ONLY
